package com.shushijuhe.shushijuheread.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.shushijuhe.shushijuheread.bean.BookMixATocLocalBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_MIX_ATOC_LOCAL_BEAN".
*/
public class BookMixATocLocalBeanDao extends AbstractDao<BookMixATocLocalBean, Long> {

    public static final String TABLENAME = "BOOK_MIX_ATOC_LOCAL_BEAN";

    /**
     * Properties of entity BookMixATocLocalBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Link = new Property(2, String.class, "link", false, "LINK");
        public final static Property Bookid = new Property(3, String.class, "bookid", false, "BOOKID");
        public final static Property IsOnline = new Property(4, boolean.class, "isOnline", false, "IS_ONLINE");
    }


    public BookMixATocLocalBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BookMixATocLocalBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_MIX_ATOC_LOCAL_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"LINK\" TEXT," + // 2: link
                "\"BOOKID\" TEXT," + // 3: bookid
                "\"IS_ONLINE\" INTEGER NOT NULL );"); // 4: isOnline
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_MIX_ATOC_LOCAL_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookMixATocLocalBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(3, link);
        }
 
        String bookid = entity.getBookid();
        if (bookid != null) {
            stmt.bindString(4, bookid);
        }
        stmt.bindLong(5, entity.getIsOnline() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookMixATocLocalBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(3, link);
        }
 
        String bookid = entity.getBookid();
        if (bookid != null) {
            stmt.bindString(4, bookid);
        }
        stmt.bindLong(5, entity.getIsOnline() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BookMixATocLocalBean readEntity(Cursor cursor, int offset) {
        BookMixATocLocalBean entity = new BookMixATocLocalBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // link
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // bookid
            cursor.getShort(offset + 4) != 0 // isOnline
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookMixATocLocalBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLink(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBookid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsOnline(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BookMixATocLocalBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BookMixATocLocalBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookMixATocLocalBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
