package com.shushijuhe.shushijuheread.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shushijuhe.shushijuheread.bean.BookshelfBean;

import com.shushijuhe.shushijuheread.greendao.BookshelfBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookshelfBeanDaoConfig;

    private final BookshelfBeanDao bookshelfBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookshelfBeanDaoConfig = daoConfigMap.get(BookshelfBeanDao.class).clone();
        bookshelfBeanDaoConfig.initIdentityScope(type);

        bookshelfBeanDao = new BookshelfBeanDao(bookshelfBeanDaoConfig, this);

        registerDao(BookshelfBean.class, bookshelfBeanDao);
    }
    
    public void clear() {
        bookshelfBeanDaoConfig.getIdentityScope().clear();
    }

    public BookshelfBeanDao getBookshelfBeanDao() {
        return bookshelfBeanDao;
    }

}
